# Generated by Django 5.2.10 on 2026-04-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='is_verified',
            field=models.JSONField(default=False),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
