# Generated by Django 5.2.10 on 2026-04-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_accountuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
