# Generated by Django 4.2.4 on 2026-04-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_accountuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='registration_method',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('GOOGLE', 'Google'), ('GITHUB', 'GitHub'), ('FACEBOOK', 'Facebook'), ('X', 'X')], default='EMAIL', max_length=16),
        ),
    ]
