[program:my_django_command]

directory=/home/ubuntu/chatserver

command=/home/ubuntu/chatserver/venv/bin/python manage.py start_rabbit

autostart=true
autorestart=true
startretries=3

user=ubuntu

stdout_logfile=/home/ubuntu/chatserver/logs/my_command.out.log
stderr_logfile=/home/ubuntu/chatserver/logs/my_command.err.log

environment=PYTHONUNBUFFERED="1"
