"""
Django settings for chatserver project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
import environ
import urllib.parse

# Initialise environment variables
env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "8022-2409-40f2-1039-1ae4-1d77-16a1-92df-83c1.ngrok-free.app"
    # "local.pegionchat.com"
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    "channels",
    "chat",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    'account',
    'django_redis',
    'drf_recaptcha',
    'corsheaders',
    'taskmanagers',
    'rag_system'
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'chatserver.middleware.SecurityCheckToBlockMalaciousIPS',
    'chatserver.middleware.ProductionExceptionMiddleware'
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'chatserver.urls'

APPEND_SLASH = False

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'chatserver.wsgi.application'

ASGI_APPLICATION = "chatserver.asgi.application"


AUTH_USER_MODEL = "account.AccountUser"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

SECRET_KEY = 'django-insecure-)1^ran_db#q-87mvy-4%1!wwief=#n!18iubpjph+az)ecg^b7'
from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
}
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": env("DATABASE_NAME"),
#         "USER": env("DATABASE_USER"),
#         "PASSWORD": env("DATABASE_PASS"),
#         "HOST": env("DATABASE_HOST"),
#         "PORT": 5432,
#     }
# }
DATABASES = {}
if env("DATABASE_ENGINE") == "pgsql":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',  
            'NAME': env('DATABASE_NAME'),
            'USER': env('DATABASE_USER'),
            'PASSWORD': env('DATABASE_PASS'),
            'HOST': env('DATABASE_HOST'),
            'PORT': 5432,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',  
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'



CHANNEL_LAYERS = {
    "default":{
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts" : [("127.0.0.1", 6379)]
        }
    }
}


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}






CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_URL"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

DRF_RECAPTCHA_SECRET_KEY = os.getenv("DRF_RECAPTCHA_SECRET_KEY")
DRF_RECAPTCHA_SITE_KEY = os.getenv("DRF_RECAPTCHA_SITE_KEY")
DRF_RECAPTCHA_VERIFY_ENDPOINT = os.getenv("DRF_RECAPTCHA_VERIFY_ENDPOINT")

EMAIL_SENDER_USER = os.getenv("EMAIL_SENDER_USER")



# Email config
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST=env("EMAIL_HOST")
EMAIL_PORT=env("EMAIL_PORT")
EMAIL_USE_TLS = env("EMAIL_USE_TLS")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
EMAIL_SENDER_USER = EMAIL_HOST_USER


# Google auth config
GOOGLE_OAUTH_CLIENT_ID=env("GOOGLE_OAUTH_CLIENT_ID")
GOOGLE_OAUTH_CLIENT_SECRET=env("GOOGLE_OAUTH_CLIENT_SECRET")
 
# Must exactly match the URI registered in Google Cloud Console
# For local dev:  http://localhost:5173/auth/callback
# For production: https://yourdomain.com/auth/callback
GOOGLE_OAUTH_REDIRECT_URI=env("GOOGLE_OAUTH_REDIRECT_URI")

# GitHub auth config

GITHUB_OAUTH_CLIENT_ID=env("GITHUB_OAUTH_CLIENT_ID")
GITHUB_OAUTH_CLIENT_SECRET=env("GITHUB_OAUTH_CLIENT_SECRET")
GITHUB_OAUTH_REDIRECT_URI=env("GITHUB_OAUTH_REDIRECT_URI")

# X auth config
X_OAUTH_CLIENT_ID=env("X_OAUTH_CLIENT_ID")
X_OAUTH_CLIENT_SECRET=env("X_OAUTH_CLIENT_SECRET")
X_OAUTH_REDIRECT_URI=env("X_OAUTH_REDIRECT_URI")

# LinkedIn auth config
LINKEDIN_CLIENT_ID=env("LINKEDIN_CLIENT_ID")
LINKEDIN_REDIRECT_URI=env("LINKEDIN_REDIRECT_URI")
LINKEDIN_CLIENT_SECRET=env("LINKEDIN_CLIENT_SECRET")

# frontend URL config
FRONTEND_URL=env("FRONTEND_URL")

# Huggingface API token
HUGGINGFACE_API_TOKEN=env("HUGGINGFACE_API_TOKEN")

OPENAI_API_KEY=env("OPENAI_API_KEY")

############ Rabbit MQ config #########
TASK_SERVICE=env("TASK_SERVICE")
RMQ_USERNAME=env("RMQ_USERNAME")
RMQ_PASSWORD=env("RMQ_PASSWORD")
RMQ_HOST=env("RMQ_HOST")
RMQ_PORT=env("RMQ_PORT")

###### OPEN AI API KEY ####
OPEN_AI_KEY=env("OPEN_AI_KEY")


######## kafka confif ########
KAFKA_BOOTSTRAP_SERVERS = env("KAFKA_BOOTSTRAP_SERVERS")

from taskmanagers.task.Task_manager import TaskManager
TASK_MANAGER = TaskManager()


from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,

    "AUTH_HEADER_TYPES": ("Bearer",),

    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}