# Generated by Django 6.0.4 on 2026-07-07 18:39

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RagStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True)),
                ('uuid', models.UUIDField()),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(choices=[('PDF', 'Pdf'), ('DOCX', 'Docx'), ('TXT', 'Txt'), ('CSV', 'Csv'), ('URL', 'Url')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('PROCESSED', 'PROCESSED'), ('FAILED', 'FAILED')], max_length=50)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('file_content', models.FileField(blank=True, null=True, upload_to='rag/')),
                ('url_content', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RagChuks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rag_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag_system.ragstore')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='rag_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
