# Generated by Django 6.0.4 on 2026-07-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_system', '0002_alter_ragstore_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragstore',
            name='created_at',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
