# Generated by Django 6.0.4 on 2026-07-07 19:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_system', '0003_alter_ragstore_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragstore',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
